# Generated by Django 4.0.4 on 2022-04-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizza_topping1_alter_pizza_topping2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='toppings',
            field=models.CharField(max_length=50),
        ),
    ]
